// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_acceleration_cpp
List calc_acceleration_cpp(NumericVector x, NumericVector y, NumericVector z, NumericVector mass, double G, double softening);
RcppExport SEXP _orbitr_calc_acceleration_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP massSEXP, SEXP GSEXP, SEXP softeningSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mass(massSEXP);
    Rcpp::traits::input_parameter< double >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type softening(softeningSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_acceleration_cpp(x, y, z, mass, G, softening));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_orbitr_calc_acceleration_cpp", (DL_FUNC) &_orbitr_calc_acceleration_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_orbitr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
