# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_acceleration_cpp <- function(x, y, z, mass, G, softening = 0.0) {
    .Call(`_orbitr_calc_acceleration_cpp`, x, y, z, mass, G, softening)
}

